name: Deploy

on:
  push:
    branches:
      - main # Set a branch to deploy when pushed

jobs:
  windows-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create installer
        run: |
              sudo apt update -y && sudo apt install tar && tar -czvf test.tar.gz .github
      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: test.tar.gz
          path: test.tar.gz

      - uses: actions/download-artifact@v4
        with:
          name: icons
          path: icons

  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    needs:
      - windows-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          path: test.tar.gz

      - run: find .
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: "configure semantic-release"
        run: npm install -D semantic-release @semantic-release/github

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
